[package]
name = "wvc-datafusion"
version = { workspace = true }
edition = "2021"

[dependencies]
arrow-schema = { workspace = true }
datafusion = { workspace = true }
datafusion-expr = { workspace = true }
