[workspace]
members = [ "rust/sedona-functions", "rust/sedona-schema" ]
resolver = "2"

[workspace.package]
version = "0.0.1"
homepage = "https://github.com/wherobots/wherobots-vectorized-compute"
repository = "https://github.com/wherobots/wherobots-vectorized-compute"
description = "Apache DataFusion Comet: High performance accelerator for Apache Spark"
readme = "README.md"
edition = "2021"

# Same rust-version, arrow, and datafusion dependencies as datafusion-comet
# https://github.com/apache/datafusion-comet/blob/main/native/Cargo.toml
rust-version = "1.79"

[workspace.dependencies]
arrow = { version = "53.3.0", features = ["prettyprint", "ffi", "chrono-tz"] }
arrow-array = { version = "53.3.0" }
arrow-buffer = { version = "53.3.0" }
arrow-data = { version = "53.3.0" }
arrow-ipc = { version = "53.3.0" }
arrow-schema = { version = "53.3.0" }
async-trait = { version = "0.1.87" }
datafusion = { version = "44.0.0", default-features = false }
datafusion-common = { version = "44.0.0", default-features = false }
datafusion-functions = { version = "44.0.0", default-features = false }
datafusion-functions-nested = { version = "44.0.0", default-features = false }
datafusion-expr = { version = "44.0.0", default-features = false }
datafusion-expr-common = { version = "44.0.0", default-features = false }
datafusion-execution = { version = "44.0.0", default-features = false }
datafusion-physical-plan = { version = "44.0.0", default-features = false }
datafusion-physical-expr = { version = "44.0.0", default-features = false }
geo-traits = { version = "0.2.0" }
geo-types = { version = "0.7.15" }
geoarrow = { version = "0.3.0" }
serde_json = { version = "1" }
tokio = { version = "1.43" }
wkb = { version = "0.8.0" }
wkt = { version = "0.12.0" }
