site_name: SedonaDB
site_description: "Documentation for Apache SedonaDB"
nav:
   - Home: index.md
   - CLI Quickstart: quickstart-cli.md
   - Python Quickstart: quickstart-python.ipynb
   - Development: development.md
   - API Reference:
      - Python: reference/python.md
      - SQL: reference/sql.md
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - navigation.expand

exclude_docs: |
     snippets/*
markdown_extensions:
   - admonition
   - attr_list
   - codehilite
   - footnotes
   - toc:
        permalink: true
        toc_depth: 3
   - pymdownx.arithmatex
   - pymdownx.betterem:
        smart_enable: all
   - pymdownx.caret
   - pymdownx.critic
   - pymdownx.details
   - pymdownx.emoji
   - pymdownx.highlight
   - pymdownx.inlinehilite
   - pymdownx.magiclink
   - pymdownx.mark
   - pymdownx.smartsymbols
   - pymdownx.snippets:
        base_path: ["docs/"]
   - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
   - pymdownx.tabbed:
        alternate_style: true
   - pymdownx.tasklist:
        custom_checkbox: true
   - pymdownx.tilde
plugins:
   - search
   - macros
   - git-revision-date-localized:
        type: datetime
   - mkdocs-jupyter
   - mike:
        version_selector: false
   - glightbox:
        touchNavigation: true
        loop: false
        effect: zoom
        slide_effect: slide
        width: 100%
        height: auto
        zoomable: true
        draggable: true
        skip_classes:
          - custom-skip-class-name
          - skip-lightbox
        auto_caption: false
        caption_position: bottom
        background: white
        shadow: false
        manual: false
   - tags
   - mkdocstrings:
        enable_inventory: true
        handlers:
          python:
            paths: [python/sedonadb]
            inventories:
              - https://docs.python.org/3/objects.inv
              - https://geopandas.org/en/stable/objects.inv
              - https://pandas.pydata.org/docs/objects.inv
            options:
              docstring_section_style: list
              docstring_style: google
              line_length: 80
              separate_signature: true
              show_root_heading: true
              show_signature_annotations: true
              show_source: false
              show_symbol_type_toc: true
              signature_crossrefs: true
