[package]
name = "sedonadb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "_lib"
crate-type = ["cdylib"]

[dependencies]
adbc_core = { workspace = true }
arrow-schema = { workspace = true }
arrow-array = { workspace = true }
datafusion = { workspace = true }
datafusion-common = { workspace = true }
futures = { workspace = true }
pyo3 = "0.24.0"
sedona = { path = "../../rust/sedona", features = ["aws", "gcp", "http"] }
sedona-adbc = { path = "../../rust/sedona-adbc" }
sedona-schema = { path = "../../rust/sedona-schema" }
thiserror = { workspace = true }
tokio = { workspace = true }
