[package]
name = "sedona-functions"
version.workspace = true
homepage.workspace = true
repository.workspace = true
description.workspace = true
readme.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
arrow-schema = { workspace = true }
arrow-ipc = { workspace = true }
arrow-array = { workspace = true }
async-trait = { workspace = true }
datafusion = { workspace = true }
datafusion-expr = { workspace = true }
geo-traits = { workspace = true }
geo-types = { workspace = true }
geoarrow = { workspace = true }
sedona-schema = { path = "../sedona-schema" }
tokio = { workspace = true }
wkb = { workspace = true }
wkt = { workspace = true }
