[package]
name = "sedona"
version.workspace = true
homepage.workspace = true
repository.workspace = true
description.workspace = true
readme.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
default = ["aws", "gcp", "http"]
aws = ["dep:aws-config", "dep:aws-credential-types", "object_store/aws"]
gcp = ["object_store/gcp"]
http = ["object_store/http"]

[dependencies]
arrow-schema = { workspace = true }
arrow-array = { workspace = true }
async-trait = { workspace = true }
aws-config = { version = "1.5.17", optional = true }
aws-credential-types = { version = "1.2.0", optional = true }
datafusion = { workspace = true, default_features = false, features = ["parquet"] }
datafusion-expr = { workspace = true }
dirs = { workspace = true }
futures = { workspace = true }
geo-traits = { workspace = true }
geo-types = { workspace = true }
object_store = { workspace = true }
parking_lot = { workspace = true }
sedona-expr = { path = "../sedona-expr" }
sedona-functions = { path = "../sedona-functions" }
sedona-geoparquet = { path = "../sedona-geoparquet" }
sedona-schema = { path = "../sedona-schema" }
tokio = { workspace = true }
url = { workspace = true }
