name: python-wheels

on:
  pull_request:
    branches:
      - main
    paths:
      - 'ci/scripts/**'
      - '.github/workflows/python-wheels.yml'
  push:
    branches:
      - main
      - 'maint-**'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.repository }}-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  macOS-arm64:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==3.1.4

      - uses: Swatinem/rust-cache@v2
        with:
          # Update this key to force a new cache
          prefix-key: "python-wheel-macOS-latest-v1"

      - name: Clone vcpkg
        uses: actions/checkout@v4
        with:
          repository: microsoft/vcpkg
          ref: "2025.06.13"
          path: vcpkg

      - name: Build and test wheels (sedonadb)
        run: |
          cd ci/scripts
          ./wheels-build-macos.sh sedonadb
        env:
          VCPKG_ROOT: ${{ github.workspace }}/vcpkg
          CIBW_SKIP: "cp314*"
          CIBW_TEST_REQUIRES: pytest adbc_driver_manager geoarrow-pyarrow geopandas duckdb
          CIBW_TEST_COMMAND: pytest {package}/tests -vv

      # Some wheels for test dependencies aren't available for Python 3.14
      - name: Build wheels for Python 3.14 (sedonadb)
        run: |
          cd ci/scripts
          ./wheels-build-macos.sh sedonadb
        env:
          VCPKG_ROOT: ${{ github.workspace }}/vcpkg
          CIBW_BUILD: "cp314*"
          CIBW_TEST_COMMAND: python -c 'import sedonadb; sedonadb.connect()' && echo 'Success!'

      - uses: actions/upload-artifact@v4
        with:
          name: release-wheels-macOS-arm64
          path: python/sedonadb/dist/*.whl
